### PR TITLE
Update setup dependencies + fix YAML bug + fix diagram + fix typo in docstring + tutorial setup

### PR DESCRIPTION
**Pull request by MilagrosMarin**
This PR was intended to: 
- [x] Fix typo in `model_description` docstring

This PR has also introduced the following changes:
- [x] Color update in the flowchart images and update the name as in `element-calcium-imaging`
- [x] Set up of `dj.config()` for the tutorial / DevContainers is now in `tutorial_pipeline.py` instead of `__init__.py`
- [x] The packaging requirements of `elements` in `setup.py` will now install directly from GitHub instead of PyPI (no longer updated) 
     - [x] Consequently, fix the path directories used in the tutorial 
     - [x] Update the outputs of the tutorial 
- [x] Minor changes in the tutorial markdown, aligning it with `element-array-ephys` tutorial

This PR also addresses the bug introduced by the latest update to the YAML dependency with the following error emerged in `element_deeplabcut/readers/dlc_reader.py`:

`AttributeError: safe_load() has been removed, use yaml = YAML(typ= safe , pure=True) yaml.load(...) instead of file /workspaces/element-deeplabcut/element_deeplabcut/readers/dlc_reader.py , line 148 self._yml = yaml.safe_load(f)`

By changing it as follows: 

`                yaml_loader = yaml.YAML(typ='safe', pure=True)
                self._yml = yaml_loader.load(f)`

These adjustments, along with the tutorial, have been tested successfully in Codespaces.

### CODE REVIEW

**Comment by ttngu207** [comment]
This introduces changes to the table definition on the database side, and the change won't propagate backward. 
So unless there is a very compelling need to do this change, I'd rather not touch it.

**Comment by MilagrosMarin** [comment]
> This introduces changes to the table definition on the database side, and the change won't propagate backward. So unless there is a very compelling need to do this change, I'd rather not touch it.

@ttngu207 I would recommend preserving the change at line 310, as it specifically corrects the description (docstring), aligning with the definition already provided at line 332 (model_description).

**Comment by MilagrosMarin** [comment]
I have reverted one of the changes and updated the title of this minor PR.

**Comment by MilagrosMarin** [comment]
I have incorporated new modifications into this PR.

**Review by kushalbakshi — COMMENTED** [review]
Hi @MilagrosMarin, thank you for making these changes. It looks like style tests and the test DevContainer builds are failing. Once these are addressed we should be able to finish the review and merge. Let me know if you need any help getting those resolved.

**Comment by MilagrosMarin** [comment]
> Hi @MilagrosMarin, thank you for making these changes. It looks like style tests and the test DevContainer builds are failing. Once these are addressed we should be able to finish the review and merge. Let me know if you need any help getting those resolved.

@kushalbakshi I've successfully re-tested the Dev Container, and it built and launched without issues. Additionally, I have also re-tested the tutorial, and it is functioning correctly. However, the `element-deeplabcut` tests require updating. If the errors you've highlighted stem from these outdated files, I recommend addressing this in a subsequent PR.

**Comment by kushalbakshi** [comment]
> > Hi @MilagrosMarin, thank you for making these changes. It looks like style tests and the test DevContainer builds are failing. Once these are addressed we should be able to finish the review and merge. Let me know if you need any help getting those resolved.
> 
> @kushalbakshi I've successfully re-tested the Dev Container, and it built and launched without issues. Additionally, I have also re-tested the tutorial, and it is functioning correctly. However, the `element-deeplabcut` tests require updating. If the errors you've highlighted stem from these outdated files, I recommend addressing this in a subsequent PR.

We cannot merge until at least the style tests have passed, which just requires applying Black formatting to all the files in the repo. I'm not sure what is causing the error with the `devcontainer-build` but I recommend you find the cause in the error stack and state whether and why this is expected before merging. 

Also, do you expect the devcontainer build to take 74 minutes? That's how long it is taking before the error occurs.

**Comment by MilagrosMarin** [comment]
> > > Hi @MilagrosMarin, thank you for making these changes. It looks like style tests and the test DevContainer builds are failing. Once these are addressed we should be able to finish the review and merge. Let me know if you need any help getting those resolved.
> > 
> > 
> > @kushalbakshi I've successfully re-tested the Dev Container, and it built and launched without issues. Additionally, I have also re-tested the tutorial, and it is functioning correctly. However, the `element-deeplabcut` tests require updating. If the errors you've highlighted stem from these outdated files, I recommend addressing this in a subsequent PR.
> 
> We cannot merge until at least the style tests have passed, which just requires applying Black formatting to all the files in the repo. I'm not sure what is causing the error with the `devcontainer-build` but I recommend you find the cause in the error stack and state whether and why this is expected before merging.
> 
> Also, do you expect the devcontainer build to take 74 minutes? That's how long it is taking before the error occurs.



> > > Hi @MilagrosMarin, thank you for making these changes. It looks like style tests and the test DevContainer builds are failing. Once these are addressed we should be able to finish the review and merge. Let me know if you need any help getting those resolved.
> > 
> > 
> > @kushalbakshi I've successfully re-tested the Dev Container, and it built and launched without issues. Additionally, I have also re-tested the tutorial, and it is functioning correctly. However, the `element-deeplabcut` tests require updating. If the errors you've highlighted stem from these outdated files, I recommend addressing this in a subsequent PR.
> 
> We cannot merge until at least the style tests have passed, which just requires applying Black formatting to all the files in the repo. I'm not sure what is causing the error with the `devcontainer-build` but I recommend you find the cause in the error stack and state whether and why this is expected before merging.
> 
> Also, do you expect the devcontainer build to take 74 minutes? That's how long it is taking before the error occurs.

My apologies for any confusion earlier. Initially, I misunderstood that the failing style tests and test builds were related to Pytests, not GitHub Action tests. I've taken steps to address the GitHub Action tests by applying Black formatting to specific files, and these changes have resolved the issues. This changes have also optimized the `devcontainer-build` duration from 74 minutes to 18 minutes. All the checks, including style tests, have now passed successfully.

Thank you for your patience and guidance. If there are any further recommendations or specific areas that need attention, please let me know, and I'll promptly address them.

**Review by kushalbakshi — APPROVED** [review]

**Review by kushalbakshi — CHANGES_REQUESTED** [review]
Looks good @MilagrosMarin. Just needs the CHANGELOG and `version.py` updated.

**Comment by MilagrosMarin** [comment]
> Looks good @MilagrosMarin. Just needs the CHANGELOG and `version.py` updated.

CHANGELOG and `version.py` updated, and YAML object added in `model.py` as suggested in parallel PR#102.

**Review by kushalbakshi — APPROVED** [review]
Looks good, @MilagrosMarin. Thank you for making these changes.

**Pull request merged**
